Add basic functionality to add, delete, and complete todo items
leehornsoftwire/DevOps-Course-Starter pull request #2
Opened 2021-10-27 15:53 UTC by leehornsoftwire

module_1 pull request

2021-11-02 16:10 UTC, JoshAdamPowell requested changes
Looks good apart from the fact that it fails for the empty case 😅. Please fix that before we merge this!

2021-11-02 16:10 UTC, JoshAdamPowell commented on todo_app/data/session_items.py
> +        items_by_id_as_strings: Dict[str, Dict[str, str]] = session.get("_items_by_id")
This code doesn't handle the case where we have no tasks - it causes the page to fail. I think the solution is to provide reasonable defaults, or maybe return early.

2021-11-02 16:10 UTC, JoshAdamPowell commented on todo_app/templates/index.html
> +    <input type="text" id="title" name="title">
minor but might be nice for this to have a `required` attribute

2021-11-04 11:24 UTC, merged

2021-11-10 09:15 UTC, JackMead commented
Thanks for fixing that up, happy it's now merged 😄